#!/usr/bin/env bash
# =============================================================================
# bootstrap-server.sh
# -----------------------------------------------------------------------------
# Run this ONCE on a fresh Ubuntu 22.04/24.04 LTS VPS to prepare it for the
# deploy pipeline. After it finishes you can run `npm run deploy` from your
# laptop.
#
# What it does:
#   1.  Updates apt and installs base packages.
#   2.  Creates a non-root `deploy` user with sudo and your SSH key.
#   3.  Hardens SSH: key-only, no root login, no password auth.
#   4.  Configures ufw (firewall): allow 22, 80, 443; deny everything else.
#   5.  Installs fail2ban with the default sshd jail.
#   6.  Installs Node 20 LTS via NodeSource, pm2 globally, pm2-logrotate.
#   7.  Installs Nginx + certbot (snap), creates the webroot for ACME.
#   8.  Creates /var/www/airegistry with the releases/shared/current layout.
#   9.  Enables PM2's systemd unit so the app survives reboots.
#
# Usage (run as root or with sudo on the server):
#
#   curl -fsSL https://raw.githubusercontent.com/your-org/airegistry/main/deploy/bootstrap-server.sh \
#     | sudo SSH_PUBKEY="ssh-ed25519 AAAA... you@laptop" bash
#
#   ...or scp this file onto the box and run:
#     sudo SSH_PUBKEY="ssh-ed25519 AAAA..." bash bootstrap-server.sh
#
# The script is idempotent — safe to re-run.
# =============================================================================

set -euo pipefail

# ----- Configuration --------------------------------------------------------
DEPLOY_USER="${DEPLOY_USER:-deploy}"
APP_DIR="${APP_DIR:-/var/www/airegistry}"
NODE_MAJOR="${NODE_MAJOR:-20}"
SSH_PUBKEY="${SSH_PUBKEY:-}"   # MUST be set; refused otherwise.

log()  { printf "\033[1;34m[bootstrap]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[bootstrap]\033[0m %s\n" "$*" >&2; }
die()  { printf "\033[1;31m[bootstrap]\033[0m %s\n" "$*" >&2; exit 1; }

require_root() {
  if [[ $EUID -ne 0 ]]; then
    die "Must be run as root (or via sudo)."
  fi
}

# ----- Pre-flight -----------------------------------------------------------
require_root

if [[ -z "$SSH_PUBKEY" ]]; then
  die "Set SSH_PUBKEY to the public key on your laptop. Example:
  sudo SSH_PUBKEY=\"ssh-ed25519 AAAA... you@laptop\" bash bootstrap-server.sh"
fi

# Rough sanity check on the pubkey shape.
if ! [[ "$SSH_PUBKEY" =~ ^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp256)\ [A-Za-z0-9+/=]+ ]]; then
  die "SSH_PUBKEY does not look like an OpenSSH public key."
fi

log "Updating apt and installing base packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y \
  curl ca-certificates gnupg lsb-release \
  ufw fail2ban \
  build-essential git rsync unattended-upgrades \
  software-properties-common

# ----- Deploy user ----------------------------------------------------------
if id "$DEPLOY_USER" &>/dev/null; then
  log "User '$DEPLOY_USER' already exists."
else
  log "Creating user '$DEPLOY_USER'..."
  adduser --disabled-password --gecos "" "$DEPLOY_USER"
  usermod -aG sudo "$DEPLOY_USER"
fi

# Sudo without password for service control only — narrower than full NOPASSWD.
SUDOERS_FILE="/etc/sudoers.d/${DEPLOY_USER}-services"
cat > "$SUDOERS_FILE" <<EOF
# Generated by bootstrap-server.sh. Limits passwordless sudo to commands the
# deploy pipeline actually needs.
${DEPLOY_USER} ALL=(root) NOPASSWD: /bin/systemctl reload nginx, /bin/systemctl restart nginx, /usr/sbin/nginx -t
EOF
chmod 440 "$SUDOERS_FILE"
visudo -c -f "$SUDOERS_FILE" >/dev/null

# Install pubkey.
DEPLOY_HOME="$(getent passwd "$DEPLOY_USER" | cut -d: -f6)"
install -d -m 700 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$DEPLOY_HOME/.ssh"
AUTH_KEYS="$DEPLOY_HOME/.ssh/authorized_keys"
touch "$AUTH_KEYS"
chmod 600 "$AUTH_KEYS"
chown "$DEPLOY_USER:$DEPLOY_USER" "$AUTH_KEYS"
if ! grep -qxF "$SSH_PUBKEY" "$AUTH_KEYS"; then
  echo "$SSH_PUBKEY" >> "$AUTH_KEYS"
  log "Installed SSH public key for '$DEPLOY_USER'."
else
  log "SSH public key already present for '$DEPLOY_USER'."
fi

# ----- SSH hardening --------------------------------------------------------
log "Hardening sshd..."
SSHD_DROPIN="/etc/ssh/sshd_config.d/99-airegistry-hardening.conf"
cat > "$SSHD_DROPIN" <<'EOF'
# Managed by bootstrap-server.sh. Don't edit by hand.
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding no
PermitEmptyPasswords no
MaxAuthTries 3
LoginGraceTime 30
ClientAliveInterval 300
ClientAliveCountMax 2
EOF
chmod 644 "$SSHD_DROPIN"

# Validate before reloading. If the user is root-via-password right now, this
# is the moment they need to have their key already in authorized_keys.
sshd -t
systemctl reload ssh || systemctl reload sshd

# ----- Firewall -------------------------------------------------------------
log "Configuring ufw..."
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

# ----- fail2ban -------------------------------------------------------------
log "Enabling fail2ban (sshd jail)..."
cat > /etc/fail2ban/jail.d/sshd.local <<'EOF'
[sshd]
enabled  = true
port     = ssh
logpath  = %(sshd_log)s
backend  = %(sshd_backend)s
maxretry = 5
findtime = 10m
bantime  = 1h
EOF
systemctl enable --now fail2ban
systemctl restart fail2ban

# ----- Unattended security upgrades ----------------------------------------
log "Enabling unattended security upgrades..."
dpkg-reconfigure -f noninteractive unattended-upgrades

# ----- Node.js --------------------------------------------------------------
if command -v node &>/dev/null && node -v | grep -q "^v${NODE_MAJOR}\."; then
  log "Node ${NODE_MAJOR}.x already installed: $(node -v)"
else
  log "Installing Node ${NODE_MAJOR}.x from NodeSource..."
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y nodejs
fi
log "node: $(node -v), npm: $(npm -v)"

# ----- PM2 ------------------------------------------------------------------
if ! command -v pm2 &>/dev/null; then
  log "Installing PM2 globally..."
  npm install -g pm2
fi
log "pm2: $(pm2 -v)"

# Logrotate plugin so /var/log/airegistry doesn't grow forever.
sudo -u "$DEPLOY_USER" pm2 install pm2-logrotate >/dev/null 2>&1 || true
sudo -u "$DEPLOY_USER" pm2 set pm2-logrotate:max_size 50M
sudo -u "$DEPLOY_USER" pm2 set pm2-logrotate:retain 14
sudo -u "$DEPLOY_USER" pm2 set pm2-logrotate:compress true

# PM2 systemd unit so app survives reboots.
# Generates a unit file and prints a command — we run that command directly.
PM2_STARTUP_CMD=$(sudo -u "$DEPLOY_USER" pm2 startup systemd -u "$DEPLOY_USER" --hp "$DEPLOY_HOME" \
  | grep -E '^sudo ' || true)
if [[ -n "$PM2_STARTUP_CMD" ]]; then
  log "Registering PM2 with systemd..."
  bash -c "$PM2_STARTUP_CMD"
fi

# ----- App directories ------------------------------------------------------
log "Creating $APP_DIR layout..."
install -d -m 755 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$APP_DIR"
install -d -m 755 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$APP_DIR/releases"
install -d -m 750 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$APP_DIR/shared"
install -d -m 755 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "/var/log/airegistry"

# Empty .env.production placeholder so first deploy doesn't fail. The real one
# is rsync'd by deploy.sh from deploy/secrets/.env.production on your laptop.
touch "$APP_DIR/shared/.env.production"
chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/shared/.env.production"
chmod 600 "$APP_DIR/shared/.env.production"

# ----- Nginx ----------------------------------------------------------------
if ! command -v nginx &>/dev/null; then
  log "Installing nginx..."
  apt-get install -y nginx
fi
install -d -m 755 /var/www/letsencrypt
systemctl enable --now nginx

# Disable the default site so the AI Registry one becomes canonical.
if [[ -L /etc/nginx/sites-enabled/default ]]; then
  rm /etc/nginx/sites-enabled/default
fi

# ----- certbot (via snap, recommended path) --------------------------------
if ! command -v certbot &>/dev/null; then
  if ! command -v snap &>/dev/null; then
    log "Installing snapd..."
    apt-get install -y snapd
    systemctl enable --now snapd.socket
    ln -sf /var/lib/snapd/snap /snap
  fi
  log "Installing certbot via snap..."
  snap install core; snap refresh core
  snap install --classic certbot
  ln -sf /snap/bin/certbot /usr/bin/certbot
fi

# ----- Done -----------------------------------------------------------------
cat <<EOF

──────────────────────────────────────────────────────────────────────────────
  Bootstrap complete.
──────────────────────────────────────────────────────────────────────────────

Next steps, run from your laptop:

  1.  Test SSH as the deploy user:
        ssh ${DEPLOY_USER}@<this-server-ip>

  2.  Add a Host entry to ~/.ssh/config matching DEPLOY_SSH_HOST in
      deploy/deploy.config.sh.

  3.  Drop your real production env at deploy/secrets/.env.production
      (chmod 600), then:
        npm run deploy

  4.  After the first successful deploy, issue the TLS cert on the server:
        sudo cp /path/to/cloned/deploy/nginx/airegistry.mu.conf \\
                /etc/nginx/sites-available/
        sudo ln -s /etc/nginx/sites-available/airegistry.mu.conf \\
                   /etc/nginx/sites-enabled/airegistry.mu.conf
        sudo nginx -t
        sudo certbot --nginx -d airegistry.mu -d www.airegistry.mu \\
             --redirect --hsts --staple-ocsp \\
             -m admin@airegistry.mu --agree-tos -n
        sudo systemctl reload nginx

──────────────────────────────────────────────────────────────────────────────
EOF
